package com.yowyob.common.event;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.time.Instant;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Tests pour BaseEvent
 *
 * @author YowYob Team 4GI-ENSPY Promo 2027
 * @author HEUDEP DJANDJA BRIAN B 22P405
 * @version 1.0.0
 */
@DisplayName("BaseEvent Tests")
class BaseEventTest {

    private static class TestEvent extends BaseEvent {
        public TestEvent(String eventType) {
            super(eventType);
        }

        public TestEvent(String eventId, Instant timestamp, String eventType) {
            super(eventId, timestamp, eventType);
        }
    }

    @Test
    @DisplayName("Devrait créer un événement avec génération automatique d'ID")
    void shouldCreateEventWithAutoGeneratedId() {
        TestEvent event = new TestEvent("TEST_EVENT");

        assertThat(event.getEventId()).isNotNull();
        assertThat(event.getEventId()).isNotEmpty();
        assertThat(event.getEventType()).isEqualTo("TEST_EVENT");
        assertThat(event.getTimestamp()).isNotNull();
        assertThat(event.getTimestamp()).isBeforeOrEqualTo(Instant.now());
    }

    @Test
    @DisplayName("Devrait créer un événement avec ID et timestamp spécifiques")
    void shouldCreateEventWithSpecificIdAndTimestamp() {
        String eventId = "custom-event-id";
        Instant timestamp = Instant.parse("2025-01-15T10:30:00Z");

        TestEvent event = new TestEvent(eventId, timestamp, "TEST_EVENT");

        assertThat(event.getEventId()).isEqualTo(eventId);
        assertThat(event.getTimestamp()).isEqualTo(timestamp);
        assertThat(event.getEventType()).isEqualTo("TEST_EVENT");
    }

    @Test
    @DisplayName("Devrait générer des IDs différents pour chaque événement")
    void shouldGenerateDifferentIdsForEachEvent() {
        TestEvent event1 = new TestEvent("TEST_EVENT");
        TestEvent event2 = new TestEvent("TEST_EVENT");

        assertThat(event1.getEventId()).isNotEqualTo(event2.getEventId());
    }
}